### ISSUE TITLE
Can't overwrite existing files?

### ISSUE THREAD

**Issue by ghost** [lVlyke/starfield-mod-loader#13]
https://www.nexusmods.com/fallout4/mods/81353 won't work :c

**Comment by lVlyke** [comment]
Unfortunately overwriting game files is not currently supported, however upcoming version 0.8.0 will have support for this.

**Comment by lVlyke** [comment]
This is now supported with version [0.8.0](https://github.com/lVlyke/starfield-mod-loader/releases/tag/v0.8.0).
