### ISSUE TITLE
Some mods can't be added (Unrecognized mod format)

### ISSUE THREAD

**Issue by Gliptal** [lVlyke/starfield-mod-loader#3]
It seems some mods can't be added: attempting to drag and drop the latest [StarUI Inventory](https://www.nexusmods.com/starfield/mods/773?tab=files&file_id=16720) for example gives this error:

![Screenshot 2023-10-10 170552](https://github.com/lVlyke/starfield-mod-loader/assets/3907646/ca0954e7-ffcb-4c54-8586-6adb153fbbc4)

It appears the issue is limited to the drag&drop action; `Import Mod` works fine.

**Comment by lVlyke** [comment]
Hello, thanks for the bug report.

Unfortunately I'm not able to reproduce this issue on my end. What OS version are you running?

Also, just to be clear, I see you mentioned `Import Mod` works. Does `Add Mod` also work or does it show the same error as drag & drop?

**Comment by lVlyke** [comment]
I just released a [new version](https://github.com/lVlyke/starfield-mod-loader/releases/tag/v0.4.0) that includes a few changes to drag & drop mod imports. Try it out if you get a chance and let me know if it fixes the issue you're seeing.

**Comment by Gliptal** [comment]
It seems to be fixed on my end, thanks!
