### ISSUE TITLE
Infinitely syncing mods

### ISSUE THREAD

**Issue by scrubborn** [lVlyke/starfield-mod-loader#6]
I have 3 simple mods I'm trying to load to test this out, but upon hitting activate mods for the first time it just infinitely says "syncing mods". Now I seem to be locked out, as i can't cancel the process, and restarting the app auto restarts the infinite syncing. I'm on garuda hyprland, and running the latest release of the mod manager.

**Comment by maxfinnsjo** [comment]
Hi, I have the exact same issue. On EndeavourOS.

**Comment by lVlyke** [comment]
Hi, thanks for the report. Unfortunately I'm not able to reproduce this issue on my EndeavourOS installation. Are there any errors in the `app.log` file in the application directory?

**Comment by scrubborn** [comment]
I'm not getting any errors, theres only one line added to the log when I start the app with this bug - 

[2023-12-02 15:36:44.985] [info]  Deploying profile Base Profile

**Comment by lVlyke** [comment]
I just released version [0.5.1](https://github.com/lVlyke/starfield-mod-loader/releases/tag/v0.5.1) which adds some additional error logging during mod deployment. When you get a chance, please try this version and let me know if you see any new errors show up in the log.

What filesystem are you using?

**Comment by scrubborn** [comment]
Cool, that gave more useful info. I also just found that I can deploy mods if I aren't trying to use a mod with a plugin.  
  
[2023-12-02 15:56:22.832] [info]  Deploying profile Base
[2023-12-02 15:56:22.833] [error] Mod deployment failed:  Error: Unable to write plugins list.
    at ElectronLoader.deployProfile (/home/scrubby/Tools and Applications/starfield-mod-loader-linux-x64/resources/app/electron.js:1140:27)
    at /home/scrubby/Tools and Applications/starfield-mod-loader-linux-x64/resources/app/electron.js:285:25
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:88656)
    at WebContents.emit (node:events:514:28)

I'm using ext4 but the mod manager is on a different ext4 drive from the game.

**Comment by lVlyke** [comment]
That error can happen when the directory of the profile's Plugin list path doesn't exist. Try checking your profile and make sure that directory exists.

**Comment by scrubborn** [comment]
Can confirm the filepath to the plugins.txt is correct, copying and pasting it into my file manager pulls it up no issue.

**Comment by lVlyke** [comment]
I believe I've found the problem and just released a [new version](https://github.com/lVlyke/starfield-mod-loader/releases/tag/v0.5.2) with the fix. Let me know if this resolves the issue.

**Comment by scrubborn** [comment]
The new version appears to work without issue! I am ecstatic to have a functional native linux mod manger for this game, thanks.  
  
Closing issue.
